/**
 * PublicInvoicePage — what a customer sees when they open their invoice link.
 *
 * ── Why this page exists ─────────────────────────────────────────────────────
 *
 * utils/qr.js builds every printed invoice's QR as
 * `{PUBLIC_APP_URL}/customer-invoices/{token}` and its comment calls that "the
 * document's PUBLIC share link". App.jsx has that path behind
 * RequirePermission, so until now scanning the QR on your own invoice took you
 * to a login screen.
 *
 * This page is mounted at the SAME path, but only when there is no session —
 * see App.jsx, next to the equivalent `{!user && …}` guard on the landing page.
 * So:
 *
 *   staff, logged in  → the CustomerInvoicesPage deep link, as before
 *   customer, no auth → this page
 *
 * Mounting it on the same path is the point. There are already QR codes printed
 * on paper invoices in customers' hands, and those URLs have to keep working.
 *
 * ── Why it is a redirect and not a rendered invoice ──────────────────────────
 *
 * The backend already renders the real thing — the same themed PDF the workshop
 * prints, via the auto_share_theme the settings screen configures. Rebuilding
 * that layout in React would be a second implementation of the invoice, free to
 * drift from the printed one on GST splits, discounts and warranty text.
 *
 * So this page is a courtesy shell around a redirect: it names the business
 * while the PDF loads, and gives a customer on a browser that will not display
 * a PDF inline something to tap.
 *
 * ── Why it is parameterised ─────────────────────────────────────────────────
 *
 * The advance receipt voucher needs exactly this page, differing in two
 * strings: which endpoint to open, and the word the customer reads while it
 * loads. Copying the file to change those would leave two shells to keep in
 * step on the timeout, the fallback link and the wording — so the props exist
 * instead, and both routes mount this one component. See App.jsx.
 */

import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000';

export default function PublicInvoicePage({
  // Defaults reproduce the invoice link exactly, so the existing route and the
  // QR codes already printed on paper are untouched by this becoming shared.
  endpoint = 'customer-invoice',
  noun = 'invoice',
} = {}) {
  const { token } = useParams();
  const [slow, setSlow] = useState(false);

  const href = token
    ? `${API_URL}/api/public/documents/${endpoint}/${encodeURIComponent(token)}`
    : null;

  useEffect(() => {
    if (!href) return;

    // replace(), not assign(): the customer arrived here from a WhatsApp link,
    // and Back should return them to the chat rather than bouncing off this
    // page into the redirect again.
    window.location.replace(href);

    // The PDF is generated by Puppeteer on demand, so a cold render is not
    // instant. If nothing has happened after a few seconds the customer is
    // probably on a browser that declined to navigate to it — give them a
    // link rather than a blank screen.
    const t = setTimeout(() => setSlow(true), 4000);
    return () => clearTimeout(t);
  }, [href]);

  return (
    <div style={{
      minHeight: '100vh', display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center', gap: 14,
      padding: 24, textAlign: 'center',
      fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
      color: '#111827', background: '#f9fafb',
    }}>
      <div style={{ fontSize: 22, fontWeight: 700, letterSpacing: '-0.01em' }}>Spinoto</div>
      <div style={{ fontSize: 13, color: '#6b7280' }}>Mechanic in Minutes</div>

      {!token ? (
        <p style={{ marginTop: 18, color: '#b91c1c', fontSize: 15 }}>
          This {noun} link is incomplete. Please use the full link from your message.
        </p>
      ) : (
        <>
          <p style={{ marginTop: 18, fontSize: 15, color: '#374151' }}>
            Opening your {noun}…
          </p>
          {/* Always rendered, not only on the slow path — a customer whose
              browser blocked the automatic navigation would otherwise wait
              four seconds looking at nothing they can act on. */}
          <a
            href={href}
            style={{
              marginTop: 4, fontSize: 15, fontWeight: 600,
              color: '#0f766e', textDecoration: 'underline',
            }}
          >
            Tap here if it doesn’t open automatically
          </a>
          {slow && (
            <p style={{ marginTop: 10, fontSize: 13, color: '#6b7280', maxWidth: 340 }}>
              Taking longer than usual. If the {noun} still doesn’t open, reply to
              our message and we’ll send it across.
            </p>
          )}
        </>
      )}
    </div>
  );
}
